[package]
name    = "datacules-agentdb-python"
version = "0.3.3"
edition = "2021"

[lib]
name      = "agentdb"
crate-type = ["cdylib"]

[dependencies]
agentdb = { package = "datacules-agentdb", path = "..", features = ["python"] }
pyo3    = { version = "0.21", features = ["extension-module"] }
serde_json = "1"
