[package]
name    = "datacules-agentdb-node"
version = "0.4.4"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
agentdb = { package = "datacules-agentdb", path = ".." }
napi       = { version = "2", features = ["napi8", "serde-json"] }
napi-derive = "2"
serde_json = "1"

[build-dependencies]
napi-build = "2"
